# Generated by Django 6.0.4 on 2026-04-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_apikey_tier_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="stripe_customer_id",
            new_name="lemonsqueezy_customer_id",
        ),
    ]
