# Generated by Django 6.0.4 on 2026-09-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_harden_api_keys_and_usage'),
        ('api', '0008_billingevent_profile_customer_portal_url_and_more'),
    ]

    operations = [
    ]
