# Generated by Django 6.0.4 on 2026-09-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20260920_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillingEvent',
        ),
        migrations.RemoveField(
            model_name='billingsubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='StatusIncident',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
        migrations.RemoveConstraint(
            model_name='teaminvitation',
            name='unique_pending_team_invite',
        ),
        migrations.RemoveConstraint(
            model_name='teammembership',
            name='unique_team_membership',
        ),
        migrations.RemoveField(
            model_name='webhookdelivery',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='customer_portal_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='onboarding_completed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_ends_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_renews_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_variant_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='BillingSubscription',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='WebhookDelivery',
        ),
        migrations.DeleteModel(
            name='WebhookEndpoint',
        ),
        migrations.DeleteModel(
            name='TeamInvitation',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
    ]
